// Code generated by "stringer -type=ComputerType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LAPTOP-0]
	_ = x[DESKTOP-1]
}

const _ComputerType_name = "LAPTOPDESKTOP"

var _ComputerType_index = [...]uint8{0, 6, 13}

func (i ComputerType) String() string {
	if i < 0 || i >= ComputerType(len(_ComputerType_index)-1) {
		return "ComputerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComputerType_name[_ComputerType_index[i]:_ComputerType_index[i+1]]
}
